"""SQLModel table definitions for ctxr.fsm SQLite persistence (core lifecycle).

This module defines the *lifecycle* and *state-tree* tables that back an FSM
run: projects, FSM specs, runs, run-sessions, states, transitions, worker
artifacts, aggregates, and locks. The audit/event-journal tables live in a
sibling module so this file stays focused on the mutable lifecycle surface.

Design conventions enforced here (see also ``ctxr/fsm/sqlite/connection.py``):

* SQLite **STRICT** mode on every table. We append the STRICT clause via the
  SQLAlchemy 2.0 dialect kwarg ``sqlite_strict=True`` inside ``__table_args__``
  — this is the natively-supported, alembic-friendly path (no DDL override
  needed). ``sqlite_with_rowid=True`` is set explicitly to make the intent
  obvious; it is the default but spelling it out keeps the contract explicit
  for code review.
* SQLite ``TEXT`` for every string column — including primary keys (UUIDv7 as
  36-char hyphenated UUIDs) and timestamps (ISO-8601 UTC with millisecond
  precision). STRICT tables refuse opaque BLOB-vs-TEXT coercion, so types
  must match the storage format exactly.
* Primary keys are UUIDv7 generated by ``uuid_utils.uuid7()`` so insertion
  order matches sort order — important for cursor-style pagination over
  ``runs`` and ``states``.
* Foreign keys declare ``ondelete="CASCADE"`` where the child row genuinely
  has no meaning without its parent (states/transitions/locks/etc. under a
  run). ``fsm_specs`` cascades from ``projects`` since deleting a project
  voids its specs.
* Indexes are declared in ``__table_args__`` with explicit names matching the
  brief (``idx_runs_status_last_update`` etc.). Composite-DESC indexes use
  ``Column(...).desc()`` so SQLite emits the ``DESC`` keyword in the CREATE
  INDEX DDL.
* All datetimes are stored as ``str`` — there is no Python ``datetime`` ↔
  TEXT coercion happening here. Callers MUST format with the canonical
  ``YYYY-MM-DDTHH:MM:SS.sssZ`` shape; the repository layer (W2) owns the
  helpers for that.
* JSON-bearing columns are stored as ``str`` (canonicalised JSON text). We do
  not use SQLAlchemy's ``JSON`` type because STRICT tables only accept the
  five primitive storage classes; ``TEXT`` plus an in-code ``json.loads`` is
  the standard SQLite-JSON1 pattern.
* No FastAPI / MCP imports — this module is pure ``ctxr.fsm.sqlite``.

Import sanity check::

    uv run python -c "from ctxr.fsm.sqlite import models_core; \\
        print(sorted(models_core.metadata.tables.keys()))"
"""

from __future__ import annotations

import uuid_utils
from sqlalchemy import (
    CheckConstraint,
    Column,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
)
from sqlmodel import Field, SQLModel

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _uuid7_str() -> str:
    """Return a fresh UUIDv7 as a 36-char hyphenated string.

    UUIDv7 is the project-wide PK shape because its first 48 bits are a
    millisecond Unix timestamp — that means lexicographic order matches
    insertion order, which is exactly what we want for cursor pagination
    over ``runs`` and ``states`` tables.
    """
    return str(uuid_utils.uuid7())


# Common dialect kwargs shared by every table in this module. The dict form
# is appended to each ``__table_args__`` tuple; SQLAlchemy applies the
# ``sqlite_*`` keys when compiling DDL for the SQLite dialect (silently
# ignored on other dialects, which is the correct cross-dialect behaviour
# even though this project only targets SQLite).
_SQLITE_DIALECT_KWARGS: dict[str, bool] = {
    "sqlite_strict": True,
    "sqlite_with_rowid": True,
}


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------


class ProjectTable(SQLModel, table=True):
    """A project: the outermost grouping under which FSM specs and runs live."""

    __tablename__ = "projects"
    __table_args__ = (_SQLITE_DIALECT_KWARGS,)

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    slug: str = Field(
        sa_column=Column("slug", Text, nullable=False, unique=True, index=True),
    )
    created_at: str = Field(
        sa_column=Column("created_at", Text, nullable=False),
    )
    metadata_json: str = Field(
        default="{}",
        sa_column=Column("metadata_json", Text, nullable=False, server_default="{}"),
    )


class FsmSpecTable(SQLModel, table=True):
    """A versioned, content-addressed FSM specification belonging to a project.

    ``hash`` is the SHA-256 hex digest produced by
    :func:`ctxr.fsm.core.spec.fsm_spec_hash`; it is the *content* identity of
    the spec independent of its surrogate ``id`` PK. The UNIQUE constraint on
    ``(project_id, slug, version)`` makes the natural identity addressable.
    """

    __tablename__ = "fsm_specs"
    __table_args__ = (
        UniqueConstraint(
            "project_id",
            "slug",
            "version",
            name="idx_fsm_specs_unique",
        ),
        CheckConstraint("version >= 1", name="ck_fsm_specs_version_positive"),
        _SQLITE_DIALECT_KWARGS,
    )

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    project_id: str = Field(
        sa_column=Column(
            "project_id",
            Text,
            ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    slug: str = Field(
        sa_column=Column("slug", Text, nullable=False, index=True),
    )
    version: int = Field(
        sa_column=Column("version", Integer, nullable=False),
    )
    hash: str = Field(
        sa_column=Column("hash", Text, nullable=False),
    )
    definition_json: str = Field(
        sa_column=Column("definition_json", Text, nullable=False),
    )
    created_at: str = Field(
        sa_column=Column("created_at", Text, nullable=False),
    )


class RunTable(SQLModel, table=True):
    """A single execution of an FSM spec.

    The composite indexes mirror the read-path the API and CLI take most
    often: list-by-status sorted by ``last_update_at DESC`` (the "what is
    happening right now" query) and list-by-project sorted by ``started_at
    DESC`` (the per-project run history). ``parent_run_id`` is its own index
    to make the resumed-from-run / supersedes-run lookups O(1).

    ``fsm_spec_hash`` is the spec hash *as observed at run start* — this is
    the "hash lock" the engine consults to decide whether mid-run spec drift
    should pause the run.
    """

    __tablename__ = "runs"
    __table_args__ = (
        Index(
            "idx_runs_status_last_update",
            "status",
            Column("last_update_at", Text).desc(),
        ),
        Index(
            "idx_runs_project_started",
            "project_id",
            Column("started_at", Text).desc(),
        ),
        Index("idx_runs_parent", "parent_run_id"),
        _SQLITE_DIALECT_KWARGS,
    )

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    project_id: str = Field(
        sa_column=Column(
            "project_id",
            Text,
            ForeignKey("projects.id"),
            nullable=False,
            index=True,
        ),
    )
    fsm_spec_id: str = Field(
        sa_column=Column(
            "fsm_spec_id",
            Text,
            ForeignKey("fsm_specs.id"),
            nullable=False,
            index=True,
        ),
    )
    fsm_spec_hash: str = Field(
        sa_column=Column("fsm_spec_hash", Text, nullable=False),
    )
    status: str = Field(
        sa_column=Column("status", Text, nullable=False, index=True),
    )
    current_state: str | None = Field(
        default=None,
        sa_column=Column("current_state", Text, nullable=True),
    )
    next_state: str | None = Field(
        default=None,
        sa_column=Column("next_state", Text, nullable=True),
    )
    verdict: str | None = Field(
        default=None,
        sa_column=Column("verdict", Text, nullable=True),
    )
    started_at: str = Field(
        sa_column=Column("started_at", Text, nullable=False, index=True),
    )
    ended_at: str | None = Field(
        default=None,
        sa_column=Column("ended_at", Text, nullable=True),
    )
    last_update_at: str = Field(
        sa_column=Column("last_update_at", Text, nullable=False, index=True),
    )
    paused_at: str | None = Field(
        default=None,
        sa_column=Column("paused_at", Text, nullable=True),
    )
    pause_reason: str | None = Field(
        default=None,
        sa_column=Column("pause_reason", Text, nullable=True),
    )
    parent_run_id: str | None = Field(
        default=None,
        sa_column=Column(
            "parent_run_id",
            Text,
            ForeignKey("runs.id"),
            nullable=True,
        ),
    )
    resume_history_json: str = Field(
        default="[]",
        sa_column=Column(
            "resume_history_json", Text, nullable=False, server_default="[]"
        ),
    )
    args_json: str = Field(
        default="{}",
        sa_column=Column("args_json", Text, nullable=False, server_default="{}"),
    )
    metadata_json: str = Field(
        default="{}",
        sa_column=Column("metadata_json", Text, nullable=False, server_default="{}"),
    )
    transitions_count: int = Field(
        default=0,
        sa_column=Column(
            "transitions_count", Integer, nullable=False, server_default="0"
        ),
    )


class RunSessionTable(SQLModel, table=True):
    """A bound session for a run.

    A *session* is a single worker (or operator) attachment to a run. The
    same run may accumulate many session rows over its lifetime — one per
    acquire/release cycle. ``released_at IS NULL`` is the "currently
    attached" predicate; pairs with the :class:`LockTable` row for active
    holders.
    """

    __tablename__ = "run_sessions"
    __table_args__ = (
        Index("idx_run_sessions_run", "run_id", "session_id"),
        _SQLITE_DIALECT_KWARGS,
    )

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    session_id: str = Field(
        sa_column=Column("session_id", Text, nullable=False, index=True),
    )
    acquired_at: str = Field(
        sa_column=Column("acquired_at", Text, nullable=False),
    )
    released_at: str | None = Field(
        default=None,
        sa_column=Column("released_at", Text, nullable=True),
    )
    release_reason: str | None = Field(
        default=None,
        sa_column=Column("release_reason", Text, nullable=True),
    )


class StateTable(SQLModel, table=True):
    """A single state *entry* within a run (one row per state activation).

    ``entry_seq`` is the per-run monotonic counter that lets us totally
    order state activations even when wall-clock timestamps tie. The UNIQUE
    index on ``(run_id, entry_seq)`` is the safety net that makes the
    counter contract enforceable at the DB layer.
    """

    __tablename__ = "states"
    __table_args__ = (
        Index("idx_states_run_seq", "run_id", "entry_seq", unique=True),
        _SQLITE_DIALECT_KWARGS,
    )

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
    )
    state_id: str = Field(
        sa_column=Column("state_id", Text, nullable=False),
    )
    entry_seq: int = Field(
        sa_column=Column("entry_seq", Integer, nullable=False),
    )
    entered_at: str = Field(
        sa_column=Column("entered_at", Text, nullable=False),
    )
    exited_at: str | None = Field(
        default=None,
        sa_column=Column("exited_at", Text, nullable=True),
    )
    status: str = Field(
        sa_column=Column("status", Text, nullable=False),
    )
    inputs_json: str = Field(
        default="{}",
        sa_column=Column("inputs_json", Text, nullable=False, server_default="{}"),
    )
    outputs_json: str = Field(
        default="{}",
        sa_column=Column("outputs_json", Text, nullable=False, server_default="{}"),
    )
    iteration_n: int | None = Field(
        default=None,
        sa_column=Column("iteration_n", Integer, nullable=True),
    )


class TransitionTable(SQLModel, table=True):
    """A taken transition between two state entries within a run.

    ``from_state_id`` is a FK into ``states.id`` (the source state's *entry*
    row, not the FSM state name). ``to_state_id`` is the destination *FSM
    state name* — there is no FK because the destination row may not yet
    exist at the moment we record the decision.
    """

    __tablename__ = "transitions"
    __table_args__ = (
        Index("idx_transitions_run_from", "run_id", "from_state_id"),
        _SQLITE_DIALECT_KWARGS,
    )

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )
    from_state_id: str = Field(
        sa_column=Column(
            "from_state_id",
            Text,
            ForeignKey("states.id"),
            nullable=False,
        ),
    )
    to_state_id: str = Field(
        sa_column=Column("to_state_id", Text, nullable=False),
    )
    kind: str = Field(
        sa_column=Column("kind", Text, nullable=False),
    )
    predicate: str | None = Field(
        default=None,
        sa_column=Column("predicate", Text, nullable=True),
    )
    predicate_result: bool | None = Field(
        default=None,
        # SQLite STRICT mode forbids the BOOLEAN affinity — only TEXT, INTEGER,
        # REAL, BLOB, ANY are permitted. We store booleans as 0/1 integers and
        # let SQLAlchemy's default INTEGER<->bool coercion handle round-tripping.
        sa_column=Column("predicate_result", Integer, nullable=True),
    )
    decided_at: str = Field(
        sa_column=Column("decided_at", Text, nullable=False),
    )


class WorkerArtifactTable(SQLModel, table=True):
    """A captured worker prompt + structured response for a state entry.

    One state entry may produce multiple artifact rows when the state runs
    a :class:`ctxr.fsm.core.Loop` — ``iteration_n`` then disambiguates them
    in (state_id, iteration_n) order. ``prompt_hash`` is the SHA-256 hex
    digest of ``prompt_text`` used for dedup / cache keys.
    """

    __tablename__ = "worker_artifacts"
    __table_args__ = (_SQLITE_DIALECT_KWARGS,)

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )
    state_id: str = Field(
        sa_column=Column(
            "state_id",
            Text,
            ForeignKey("states.id"),
            nullable=False,
        ),
    )
    iteration_n: int | None = Field(
        default=None,
        sa_column=Column("iteration_n", Integer, nullable=True),
    )
    prompt_text: str = Field(
        sa_column=Column("prompt_text", Text, nullable=False),
    )
    prompt_hash: str = Field(
        sa_column=Column("prompt_hash", Text, nullable=False),
    )
    output_json: str = Field(
        sa_column=Column("output_json", Text, nullable=False),
    )
    validated: bool = Field(
        default=False,
        # STRICT-safe: store as INTEGER 0/1 rather than the BOOLEAN affinity
        # that SQLite STRICT mode refuses.
        sa_column=Column("validated", Integer, nullable=False, server_default="0"),
    )
    created_at: str = Field(
        sa_column=Column("created_at", Text, nullable=False),
    )


class AggregateTable(SQLModel, table=True):
    """A persisted across-state aggregation result.

    ``field`` is the path on the consuming state's input bag the aggregate
    feeds. ``from_state_ids_json`` is a JSON array of source state row ids
    (``states.id`` values, not FSM state names) so the lineage is
    reconstructible without re-running the aggregator.
    """

    __tablename__ = "aggregates"
    __table_args__ = (_SQLITE_DIALECT_KWARGS,)

    id: str = Field(
        default_factory=_uuid7_str,
        sa_column=Column("id", Text, primary_key=True, nullable=False),
    )
    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )
    field: str = Field(
        sa_column=Column("field", Text, nullable=False),
    )
    from_state_ids_json: str = Field(
        sa_column=Column("from_state_ids_json", Text, nullable=False),
    )
    merged_length: int = Field(
        sa_column=Column("merged_length", Integer, nullable=False),
    )
    items_json: str = Field(
        sa_column=Column("items_json", Text, nullable=False),
    )
    created_at: str = Field(
        sa_column=Column("created_at", Text, nullable=False),
    )


class LockTable(SQLModel, table=True):
    """A single-row-per-run advisory lock used by the engine to serialise writers.

    ``run_id`` is *both* the primary key and a FK into ``runs.id`` — there
    is at most one lock per run at any moment. ``expires_at`` is the lease
    expiry; the engine treats a lock with ``expires_at <= now()`` as
    reclaimable.
    """

    __tablename__ = "locks"
    __table_args__ = (_SQLITE_DIALECT_KWARGS,)

    run_id: str = Field(
        sa_column=Column(
            "run_id",
            Text,
            ForeignKey("runs.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
    )
    holder_session_id: str = Field(
        sa_column=Column("holder_session_id", Text, nullable=False),
    )
    acquired_at: str = Field(
        sa_column=Column("acquired_at", Text, nullable=False),
    )
    expires_at: str = Field(
        sa_column=Column("expires_at", Text, nullable=False),
    )


# ---------------------------------------------------------------------------
# Public surface
# ---------------------------------------------------------------------------


#: The shared SQLModel/SQLAlchemy metadata object. Alembic autogenerate and
#: ad-hoc ``metadata.create_all(engine)`` calls go through this.
metadata = SQLModel.metadata


__all__ = [
    "AggregateTable",
    "FsmSpecTable",
    "LockTable",
    "ProjectTable",
    "RunSessionTable",
    "RunTable",
    "StateTable",
    "TransitionTable",
    "WorkerArtifactTable",
    "metadata",
]
